# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cook_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CookWindow(object):
    def setupUi(self, CookWindow):
        CookWindow.setObjectName("CookWindow")
        CookWindow.resize(686, 621)
        CookWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(CookWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitleWindow = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleWindow.setGeometry(QtCore.QRect(130, 20, 351, 51))
        self.labelTitleWindow.setObjectName("labelTitleWindow")
        self.labelEmployee = QtWidgets.QLabel(self.centralwidget)
        self.labelEmployee.setGeometry(QtCore.QRect(190, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelEmployee.setFont(font)
        self.labelEmployee.setObjectName("labelEmployee")
        self.labelEmployee_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelEmployee_2.setGeometry(QtCore.QRect(340, 160, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelEmployee_2.setFont(font)
        self.labelEmployee_2.setObjectName("labelEmployee_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(59, 146, 23);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 440, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.labelEmployee_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelEmployee_3.setGeometry(QtCore.QRect(10, 160, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelEmployee_3.setFont(font)
        self.labelEmployee_3.setObjectName("labelEmployee_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 310, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 410, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        CookWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CookWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 23))
        self.menubar.setObjectName("menubar")
        CookWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CookWindow)
        self.statusbar.setObjectName("statusbar")
        CookWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CookWindow)
        QtCore.QMetaObject.connectSlotsByName(CookWindow)

    def retranslateUi(self, CookWindow):
        _translate = QtCore.QCoreApplication.translate
        CookWindow.setWindowTitle(_translate("CookWindow", "MainWindow"))
        self.labelTitleWindow.setText(_translate("CookWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Панель Повара</span></p></body></html>"))
        self.labelEmployee.setText(_translate("CookWindow", "<html><head/><body><p align=\"center\">Список заказов</p></body></html>"))
        self.labelEmployee_2.setText(_translate("CookWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#b11c1c;\">Статус</span></p></body></html>"))
        self.label_3.setText(_translate("CookWindow", "<html><head/><body><p>Заказ_1:</p><p>набор блюд</p></body></html>"))
        self.pushButton.setText(_translate("CookWindow", "готовится"))
        self.pushButton_3.setText(_translate("CookWindow", "готов"))
        self.pushButton_2.setText(_translate("CookWindow", "готовится"))
        self.labelEmployee_3.setText(_translate("CookWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#b11c1c;\">Блюда</span></p></body></html>"))
        self.label_4.setText(_translate("CookWindow", "<html><head/><body><p>Заказ_2:</p><p>набор блюд</p></body></html>"))
        self.label_5.setText(_translate("CookWindow", "<html><head/><body><p>Заказ_3:</p><p>набор блюд</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CookWindow = QtWidgets.QMainWindow()
    ui = Ui_CookWindow()
    ui.setupUi(CookWindow)
    CookWindow.show()
    sys.exit(app.exec_())
